### ISSUE TITLE
External UserId not accessible like other public properties

### ISSUE THREAD

**Issue by atbyrd** [lukedoolittle/quantfabric#117]
I'm trying to access the ExteranUserId on OAuth1Credential which appears to be public. But I am getting an error.

### Error

> Nancy.RequestExecutionException: Oh noes! ---> System.MissingMethodException: Method not found: 'System.String Material.Infrastructure.Credentials.TokenCredentials.get_ExternalUserId()'.

### Relevant Code

    public class Client
    {
        readonly OAuth1Credentials Credentials;
        const string BaseApiUrl = "http://wbsapi.withings.net/v2";

        public Client(OAuth1Credentials credentials)
        {
            Credentials = credentials;
        }

        public string ActivityMeasures(DateTime startDate, DateTime endDate)
        {
            var restClient = new RestClient(BaseApiUrl)
            {
                Authenticator = OAuth1Authenticator.ForProtectedResource(Credentials.ConsumerKey,
                    Credentials.ConsumerSecret,
                    Credentials.OAuthToken,
                    Credentials.OAuthSecret)
            };
            ((OAuth1Authenticator) restClient.Authenticator).ParameterHandling = OAuthParameterHandling.UrlOrPostParameters;
            var request = new RestRequest("/measure");
            request.AddQueryParameter("action", "getactivity");
            request.AddQueryParameter("userid", Credentials.ExternalUserId);
            request.AddQueryParameter("startdateymd", startDate.ToString(CultureInfo.InvariantCulture.DateTimeFormat.SortableDateTimePattern));
            request.AddQueryParameter("enddateymd", endDate.ToString(CultureInfo.InvariantCulture.DateTimeFormat.SortableDateTimePattern));
            var response = restClient.Execute(request);
            return response.Content;
        }
    }

**Comment by lukedoolittle** [comment]
I double checked this with the unit and integration tests and both seem to run fine.

A `MissingMethodException` indicates that a particular method was found at _compile time_ but not at _runtime_. The most common cause of that, in my experience, is when there is a outdated .dll hanging around somewhere. I would do two things to troubleshoot:

- Make sure _all_ of your assemblies have the Quantfabric NuGet package installed and that all of them have the same _version_ of the package (the latest version)
- Manually clear all of the items from the executing assembly's `bin/Debug` folder

If that doesn't work then try

- Empty your `packages` directory from the root of your project, clean and rebuild
- Check that the newly repopulated `packages` directory only has the latest version of Quantfabric (1.3.7). If it has multiple that means there is a NuGet reference in one of your projects to the old package.

If that still doesn't work...then I'm not sure. I'll have to dig some more.

**Comment by atbyrd** [comment]
@lukedoolittle Thanks. I needed to update the package in the client application.
